# Generated by Django 5.1 on 2024-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone_number', 'email', 'passport_number')},
        ),
    ]
